version: '3'
services:
  jetson:
    build: .

    # Jupyter Notebook 用のポート
    ports:
    - "8888:8888"
    volumes:
      # 現在の作業フォルダをマウント
      - ./:/home/jetson-nano-servomotor
      # 現在の作業フォルダをマウント
      - /tmp/argus_socket:/tmp/argus_socket

    # GPU 関係
    runtime: nvidia
    devices:
      # WEB カメラ
      - /dev/video0:/dev/video0
      # - /dev:/dev

    # 権限の有効化
    privileged: true

    # コンテナが落ちないように
    tty: true

    # 起動後のディレクトリ
    working_dir: /home/jetson-nano-servomotor
    # working_dir: /home